apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: alex04125/order
          envFrom:
            - configMapRef:
                name: order-configmap
            - secretRef:
                name: order-secret
